services:
  - type: web
    name: gym-track
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: gym-track-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: gym-track-db
    databaseName: gym_track
    plan: free 